authorizations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import Dashboard

from .views import AuthorizationCreateView
from .views import AuthorizationDetailView
from .views import AuthorizationUpdateView
from .views import AuthorizationPublishBylawView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^add/(?P<event_pk>\d+)$', AuthorizationCreateView.as_view(), name='authorization_add'),
    url(r'^(?P<pk>\d+)/$', AuthorizationDetailView.as_view(), name="authorization_detail"),
    url(r'^(?P<pk>\d+)/publish/$', AuthorizationPublishBylawView.as_view(), name='authorization_publish'),
    url(r'^(?P<pk>\d+)/edit/$', AuthorizationUpdateView.as_view(), name="authorization_update"),
    # pylint: enable=E1120
)

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.sitemaps import FlatPageSitemap

from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    'django.contrib.flatpages.views', (r'^(?P<url>.*/)$', 'flatpage'),
)

declarations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import DeclarationCreateView
from .views import DeclarationDetailView
from .views import DeclarationPublishReceiptView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^(?P<pk>\d+)/publish/$', DeclarationPublishReceiptView.as_view(), name='declaration_publish'),
    url(r'^add/(?P<event_pk>\d+)$', DeclarationCreateView.as_view(), name='declaration_add'),
    url(r'^(?P<pk>\d+)/$', DeclarationDetailView.as_view(), name='declaration_detail'),
    # pylint: enable=E1120
)

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import EventChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclaredNonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from .views import EventPublicDetail

from .views import DeclaredNonMotorizedEventCreate
from .views import DeclaredNonMotorizedEventDetail
from .views import DeclaredNonMotorizedEventUpdate

from .views import AuthorizedNonMotorizedEventCreate
from .views import AuthorizedNonMotorizedEventDetail
from .views import AuthorizedNonMotorizedEventUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import AdditionalDataRequestView
from .views import AdditionalDataProvideView

from .views import MailToPromotersView
from .views import MailToTownHallsView
from .views import NewsListView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToPromotersView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^news/$', NewsListView.as_view(), name="news_list"),
    url(r'^calendar/(?P<activity>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', EventChoose.as_view(),
        name='event_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^declarednonmotorizedevents/choose',
        DeclaredNonMotorizedEventChoose.as_view(),
        name="declarednonmotorizedevent_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        EventPublicDetail.as_view(),
        name="event_detail"),

    # DeclaredNonMotorizedEvent urls
    url(r'^declarednonmotorizedevents/add/$',
        DeclaredNonMotorizedEventCreate.as_view(),
        name="declarednonmotorizedevent_add"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/$',
        DeclaredNonMotorizedEventDetail.as_view(),
        name="declarednonmotorizedevent_detail"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/edit/$',
        DeclaredNonMotorizedEventUpdate.as_view(),
        name="declarednonmotorizedevent_update"),

    # AuthorizedNonMotorizedEvent urls
    url(r'^authorizednonmotorizedevents/add/$',
        AuthorizedNonMotorizedEventCreate.as_view(),
        name="authorizednonmotorizedevent_add"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/$',
        AuthorizedNonMotorizedEventDetail.as_view(),
        name="authorizednonmotorizedevent_detail"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/edit/$',
        AuthorizedNonMotorizedEventUpdate.as_view(),
        name="authorizednonmotorizedevent_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<event_pk>\d+)/additional_data/add$',
        AdditionalDataRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        AdditionalDataProvideView.as_view(),
        name="additional_data_provide"),
    # pylint: enable=E1120
)

events/templates/events/access_restricted.html
{% extends "events/base.html" %}

{% url from future %}
{% load i18n %}

{% block head_title %}{% trans 'access restricted'|title %}{% endblock %}
{% block page_title %}
    <h1>{% trans "access restricted"|capfirst %}</h1>
{% endblock %}

{% block content %}
    <p>{% trans "this part of the site is restricted to authorized people only"|capfirst %}</p>
    <p><a href="{% url 'events:home_page' %}" class="btn btn-primary" role="button">{% trans "go back to home page"|capfirst %}</a></p>
{% endblock %}

events/templates/events/base.html
{% load staticfiles %}
{% load url from future %}
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <title>{{ DEPARTMENT_NUMBER }} {% block head_title %}{% endblock %}</title>
        {% block extra_head %}
        {% endblock %}
        <meta charset='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <!-- Bootstrap -->
        <link href='{% static 'events/css/bootstrap.min.css' %}' rel='stylesheet' type='text/css'>
        <link href='{% static 'events/css/font-awesome.min.css' %}' rel='stylesheet' type='text/css'>
        <link href='{% static 'events/css/default.css' %}' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
        <link href='//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.5.0/bootstrap-table.min.css' rel='stylesheet' type='text/css'>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'></script>
        <script src='https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js'></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src='//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src='{% static 'events/js/bootstrap.min.js' %}'></script>
    </head>
    <body style="background-color: {{ DEPARTMENT_BKG_COLOR }};">
        <nav class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
            <div class='container'>
                <div class='navbar-header'>
                    <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                        <span class='sr-only'>Toggle navigation</span>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                    </button>
                    <a class='navbar-brand' href='{% url 'events:home_page' %}'>
                        <img alt='{% trans 'sportive event and sustainable development'|capfirst %}' src='{% static 'events/img/manifloire_brand.png' %}'>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class='collapse navbar-collapse'>
                    <ul class='nav navbar-nav navbar-right'>
                        {% if user.is_authenticated %}
                            {% if user.promoter %}
                                <li><a href='{% url 'profile' %}'><i class="fa fa-user"></i> {{ user.username }} ({% trans 'promoter'|capfirst %} - {{ DEPARTMENT_NUMBER }})</a></li>
                                <li><a href='{% url 'events:dashboard' %}'><i class="fa fa-tasks"></i> {% trans 'dashboard'|capfirst %}</a></li>
                            {% elif user.instructor %}
                                <li><a href='{% url 'profile' %}'><i class="fa fa-user"></i> {{ user.username }} ({% trans 'instructor'|capfirst %} - {{ DEPARTMENT_NUMBER }})</a></li>
                                <li><a href='{% url 'authorizations:dashboard' %}'><i class="fa fa-tasks"></i> {% trans 'dashboard'|capfirst %}</a></li>
                            {% elif user.agent %}
                                {% if user.agent.edsragent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.edsragent.road_safety_squadron }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.brigadeagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.brigadeagent.brigade }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.ggdagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.ggdagent.ggd }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.sdisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.sdisagent.fire_and_rescue_service }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.codisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.codisagent.departmental_fire_op_center }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.cisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cisagent.fire_service }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.ddspagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.ddspagent.public_safety_direction }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.federationagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.federationagent.federation }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.serviceagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.serviceagent.service }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.townhallagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.townhallagent.commune }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.cgagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cgagent.general_council }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.agent.cgsuperior %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cgsuperior.general_council }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% endif %}
                                <li><a href='{% url 'agreements:dashboard' %}'><i class="fa fa-tasks"></i> {% trans 'dashboard'|capfirst %}</a></li>
                            {% elif user.subagent %}
                                {% if user.subagent.companyagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.subagent.companyagent.company }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.subagent.cgdagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.subagent.cgdagent.cgd }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.subagent.commissariatagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.subagent.commissariatagent.commissariat }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% elif user.subagent.cgserviceagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.subagent.cgserviceagent.cg_service }} - {{ DEPARTMENT_NUMBER }})</a></li>
                                {% endif %}
                                <li><a href='{% url 'sub_agreements:dashboard' %}'><i class="fa fa-tasks"></i> {% trans 'dashboard'|capfirst %}</a></li>
                            {% endif %}
                            <li class="active">
                                <a href='{% url 'account_logout' %}'><i class="fa fa-sign-out"></i> {% trans 'Log out' %}</a>
                            </li>
                        {% else %}
                            <li class="active">
                                <a href='{% url 'account_login' %}'><i class="fa fa-sign-in"></i> {% trans 'Log in' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %}
            <div class='container'>
                {% if messages %}
                    <br />
                    <div class='container'>
                        {% for message in messages %}
                            <div class='alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissable'>
                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                                <strong>{{message}}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                <div class='page-header'>
                    {% block page_title %}{% endblock %}
                </div>

                {% block content %}
                {% endblock %}
            </div>
        {% endblock %}

        {% block extra_body %}
        {% endblock %}

        <footer role='contentinfo'>
            <div class="container">
                <h2 class='text-center'>{% trans 'footer_text'|capfirst %}</h2>
            </div>
        </footer>
        <script src='//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.5.0/bootstrap-table.min.js'></script>
        <script>
            function dateSorter(date1, date2) {
                var date12 = date1.split('/').reverse().join('');
                var date22 = date2.split('/').reverse().join('');
                if (date12 > date22) return 1;
                if (date12 < date22) return -1;
                return 0;
            };
        </script>
        {% block extra_js %}
        {% endblock %}
    </body>
</html>

events/templates/events/declarednonmotorizedevent_detail.html
{% extends "events/event_detail.html" %}

{% load i18n %}

{% block head_title %}{% trans "declared non motorized event"|title %}{% endblock %}

{% block counter %}
    {% if not object.eventdeclaration.id and object.grouped_traffic %}
        {% include 'events/counter.html' %}
    {% endif %}
{% endblock %}

{% block related_processes %}
    {% if object.grouped_traffic %}
        {% if not object.eventdeclaration.id %}
            {% if object.ready_for_instruction %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% trans "required actions"|capfirst %}</h3>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{% url 'declarations:declaration_add' event_pk=object.id %}" class="btn" role="button">
                                {% trans "make a declaration for a non motorized event"|capfirst %}
                            </a>
                        </li>
                    </ul>
                </div>
            {% else %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% trans "some documents are still missing in your file"|capfirst %}</h3>
                    </div>
                    <div class="panel-body">
                        <p>{% trans "once these documents added to your file, you'll be able to send your declaration"|capfirst %}</p>
                        <p>{% trans "below is the list of missing documents : "|capfirst %}</p>
                    </div>
                    <ul class="list-group">
                        {% include 'events/missing_documents.html' %}
                    </ul>
                </div>
            {% endif %}
        {% endif %}
    {% else %}
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "nothing to do"|capfirst %}</h3>
            </div>
            <div class="panel-body">
                <p>{% trans "a small text to explain some things" %}</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block end_of_process %}
    {% if object.grouped_traffic %}
        {% if object.eventdeclaration.id %}
            {% if object.eventdeclaration.state == 'published' and object.eventdeclaration.receipt %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% trans "receipt has been published"|capfirst %}</h3>
                    </div>
                    <div class="panel-body">
                        <p>{% trans "you can download it by clicking on the link below" %}</p>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{{ object.eventdeclaration.receipt.url }}" target='_blank'>{% trans 'receipt'|capfirst %}</a></li>
                    </ul>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}

events/templates/events/event_panel.html
{% load i18n %}

{% block event_description %}{% endblock %}
{% if object.rnrevaluation %}
    <div id="rnr" class="panel panel-default tab-pane fade">
        {% include 'evaluations/rnrevaluation_detail.html' with evaluation=object.rnrevaluation %}
    </div>
{% endif %}
{% if object.natura2000evaluation %}
    <div id="natura2000" class="panel panel-default tab-pane fade">
        {% include 'evaluations/natura2000evaluation_detail.html' with evaluation=object.natura2000evaluation %}
    </div>
{% endif %}
{% if object.additionaldata_set.count > 0 %}
    <div id="additionaldata" class="panel panel-default tab-pane fade">
        {% include 'events/additionaldata_detail.html' %}
    </div>
{% endif %}

events/templates/events/event_panel_instructor.html
{% extends "events/event_panel.html" %}

{% load i18n %}

{% block event_description %}
<div id="event" class="panel panel-default tab-pane fade">
    {% include 'events/event_description.html' %}
</div>
{% endblock %}

events/templates/events/last_news.html
{% load i18n %}

{% if last_news %}
    <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>{% trans 'News platform' %}</strong><br/>
        {{ last_news }} : <a href="{{ last_news.page.url }}" class="alert-link">{{ last_news.page.title }}</a>
         (<a href="{% url 'events:news_list' %}">{% trans 'Last news' %}</a>)
    </div>
{% endif %}

events/templates/events/missing_documents.html
{% load i18n %}

{% if not object.event_rules %}
    <li class="list-group-item">{% trans 'event rules'|capfirst %}</li>
{% endif %}
{% if not object.promoter_commitment %}
    <li class="list-group-item">{% trans 'promoter commitment'|capfirst %}</li>
{% endif %}
{% if not object.safety_provisions %}
    <li class="list-group-item">{% trans 'safety provisions'|capfirst %}</li>
{% endif %}

events/templates/events/motorizedevent_choose.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% trans 'motorized event ground choice'|title %}{% endblock %}
{% block page_title %}
    <h1>{% trans 'select the ground of the motorized event'|capfirst %}</h1>
{% endblock %}

{% block content %}
    <div class="list-group">
        <a href="{% url 'events:publicroadmotorizedevent_choose' %}" class="list-group-item">
            <h3>{% trans 'motorized event on public road or openned to public circulation'|capfirst %}</h3>
            <ul>
                <li>{% trans 'public road : '|capfirst %}{% trans 'public road definition'|capfirst %}</li>
                <li>{% trans 'rural road : '|capfirst %}{% trans 'rural road definition'|capfirst %}</li>
                <li>{% trans 'private road openned to public circulation: '|capfirst %}{% trans 'private road openned to public circulation definition'|capfirst %}</li>
            </ul>
        </a>
        <a href="{% url 'events:motorizedrace_add' %}" class="list-group-item">
            <h3>{% trans 'motorized event on private ground'|capfirst %}</h3>
            {% trans '(item R331-18 of sport code)'|capfirst %}
            <ul>
                <li>{% trans 'a gathering with motorized vehicles and one or several drivers'|capfirst %}</li>
                <li>{% trans 'presented in an organized way for the audience'|capfirst %}</li>
                <li>{% trans 'a motorsport in its different categories'|capfirst %}</li>
            </ul>
        </a>
    </div>
{% endblock %}

events/templates/events/motorizedevent_detail.html
{% extends "events/event_detail.html" %}

{% load i18n %}

{% block head_title %}{% trans "motorized event"|title %}{% endblock %}

{% block counter %}
    {% if not object.eventauthorization.id %}
        {% include 'events/counter.html' %}
    {% endif %}
{% endblock %}

{% block related_processes %}
    {% if not object.eventauthorization.id %}
        {% if object.ready_for_instruction %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans "required actions"|capfirst %}</h3>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="{% url 'authorizations:authorization_add' event_pk=object.id %}" class="btn" role="button">
                            {% trans "request an authorization for a motorized event"|capfirst %}
                        </a>
                    </li>
                </ul>
            </div>
        {% else %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans "some documents are still missing in your file"|capfirst %}</h3>
                </div>
                <div class="panel-body">
                    <p>{% trans "once these documents added to your file, you'll be able to request an authorization"|capfirst %}</p>
                    <p>{% trans "below is the list of missing documents : "|capfirst %}</p>
                </div>
                <ul class="list-group">
                    {% include 'events/missing_documents.html' %}
                    {% if not object.commissioners  %}
                        <li class="list-group-item">{% trans 'list of commissioners posts'|capfirst %}</li>
                    {% endif %}
                    {% if not object.tech_promoter_certificate %}
                        <li class="list-group-item">{% trans 'technical promoter certificate'|capfirst %}</li>
                    {% endif %}
                    {% if not object.hourly_itinerary %}
                        <li class="list-group-item">{% trans 'hourly itinerary'|capfirst %}</li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

{% block end_of_process %}
    {% if object.eventauthorization.id %}
        {% if object.eventauthorization.state == 'published' and object.eventauthorization.bylaw %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans "bylaw has been published"|capfirst %}</h3>
                </div>
                <div class="panel-body">
                    <p>{% trans "you can download it by clicking on the link below" %}</p>
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><a href="{{ object.eventauthorization.bylaw.url }}" target='_blank'>{% trans 'bylaw'|capfirst %}</a></li>
                </ul>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}