authorizations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import Dashboard

from .views import AuthorizationCreateView
from .views import AuthorizationDetailView
from .views import AuthorizationUpdateView
from .views import AuthorizationPublishBylawView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^add/(?P<event_pk>\d+)$', AuthorizationCreateView.as_view(), name='authorization_add'),
    url(r'^(?P<pk>\d+)/$', AuthorizationDetailView.as_view(), name="authorization_detail"),
    url(r'^(?P<pk>\d+)/publish/$', AuthorizationPublishBylawView.as_view(), name='authorization_publish'),
    url(r'^(?P<pk>\d+)/edit/$', AuthorizationUpdateView.as_view(), name="authorization_update"),
    # pylint: enable=E1120
)

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.sitemaps import FlatPageSitemap

from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    'django.contrib.flatpages.views', (r'^(?P<url>.*/)$', 'flatpage'),
)

declarations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import DeclarationCreateView
from .views import DeclarationDetailView
from .views import DeclarationPublishReceiptView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^(?P<pk>\d+)/publish/$', DeclarationPublishReceiptView.as_view(), name='declaration_publish'),
    url(r'^add/(?P<event_pk>\d+)$', DeclarationCreateView.as_view(), name='declaration_add'),
    url(r'^(?P<pk>\d+)/$', DeclarationDetailView.as_view(), name='declaration_detail'),
    # pylint: enable=E1120
)

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import EventChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclaredNonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from .views import EventPublicDetail

from .views import DeclaredNonMotorizedEventCreate
from .views import DeclaredNonMotorizedEventDetail
from .views import DeclaredNonMotorizedEventUpdate

from .views import AuthorizedNonMotorizedEventCreate
from .views import AuthorizedNonMotorizedEventDetail
from .views import AuthorizedNonMotorizedEventUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import AdditionalDataRequestView
from .views import AdditionalDataProvideView

from .views import MailToPromotersView
from .views import MailToTownHallsView
from .views import NewsListView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToPromotersView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^news/$', NewsListView.as_view(), name="news_list"),
    url(r'^calendar/(?P<activity>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', EventChoose.as_view(),
        name='event_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^declarednonmotorizedevents/choose',
        DeclaredNonMotorizedEventChoose.as_view(),
        name="declarednonmotorizedevent_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        EventPublicDetail.as_view(),
        name="event_detail"),

    # DeclaredNonMotorizedEvent urls
    url(r'^declarednonmotorizedevents/add/$',
        DeclaredNonMotorizedEventCreate.as_view(),
        name="declarednonmotorizedevent_add"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/$',
        DeclaredNonMotorizedEventDetail.as_view(),
        name="declarednonmotorizedevent_detail"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/edit/$',
        DeclaredNonMotorizedEventUpdate.as_view(),
        name="declarednonmotorizedevent_update"),

    # AuthorizedNonMotorizedEvent urls
    url(r'^authorizednonmotorizedevents/add/$',
        AuthorizedNonMotorizedEventCreate.as_view(),
        name="authorizednonmotorizedevent_add"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/$',
        AuthorizedNonMotorizedEventDetail.as_view(),
        name="authorizednonmotorizedevent_detail"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/edit/$',
        AuthorizedNonMotorizedEventUpdate.as_view(),
        name="authorizednonmotorizedevent_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<event_pk>\d+)/additional_data/add$',
        AdditionalDataRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        AdditionalDataProvideView.as_view(),
        name="additional_data_provide"),
    # pylint: enable=E1120
)

authorizations/forms.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from ddcs_loire.utils import GenericForm

from crispy_forms.layout import Submit, Layout, Fieldset
from crispy_forms.bootstrap import FormActions

from .models import EventAuthorization


class AuthorizationForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = EventAuthorization
        exclude = [
            'event',
            'creation_date',
            'dispatch_date',
            'state',
            'concerned_cities',
            'concerned_services',
            'ddsp_concerned',
            'edsr_concerned',
            'ggd_concerned',
            'sdis_concerned',
            'cg_concerned',
            'bylaw',
        ]

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(AuthorizationForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                FormActions(
                        Submit('save', _('ask for the authorization').capitalize())
                )
        )


class AuthorizationDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = EventAuthorization
        exclude = [
            'event',
            'creation_date',
            'dispatch_date',
            'state',
            'bylaw',
        ]

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(AuthorizationDispatchForm, self).__init__(*args, **kwargs)
        if settings.DEPARTMENT_SETTINGS['EDSR_OR_GGD'] == 'GGD':
            self.fields['ggd_concerned'].initial = True
            self.fields['ggd_concerned'].widget.attrs['disabled'] = True
            self.fields['edsr_concerned'].initial = False
            self.fields['edsr_concerned'].widget.attrs['disabled'] = False
        elif settings.DEPARTMENT_SETTINGS['EDSR_OR_GGD'] == 'GGD':
            self.fields['ggd_concerned'].initial = False
            self.fields['ggd_concerned'].widget.attrs['disabled'] = False
            self.fields['edsr_concerned'].initial = True
            self.fields['edsr_concerned'].widget.attrs['disabled'] = True
        self.helper.layout = Layout(
            Fieldset(
                _('agreements required').capitalize(),
                'ddsp_concerned',
                'edsr_concerned',
                'ggd_concerned',
                'sdis_concerned',
                'cg_concerned',
                'concerned_cities',
                'concerned_services',
            ),
            FormActions(
                Submit('save', _('dispatch').capitalize())
            )
        )


class AuthorizationPublishBylawForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = EventAuthorization
        fields = ('bylaw', )

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(AuthorizationPublishBylawForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            Fieldset(
                _('choose the bylaw file').capitalize(),
                'bylaw',
            ),
            FormActions(
                Submit('save', _('publish bylaw').capitalize())
            )
        )

    def clean_bylaw(self):
        data = self.cleaned_data['bylaw']
        if not data:
            raise forms.ValidationError(_('You must specify a bylaw file'))
        return data

authorizations/views.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from declarations.models import EventDeclaration

from events.decorators import promoter_required
from events.models import Event
from events.models import News

from .decorators import instructor_required

from .forms import AuthorizationPublishBylawForm
from .forms import AuthorizationForm
from .forms import AuthorizationDispatchForm

from .models import EventAuthorization


class Dashboard(ListView):  # pylint: disable=R0901
    model = EventAuthorization

    @method_decorator(instructor_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        instructor = self.request.user.instructor
        return EventAuthorization.objects.to_process().for_instructor(instructor).closest_first()

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        instructor = self.request.user.instructor
        context['declarations'] = EventDeclaration.objects.to_process().for_instructor(instructor).closest_first()
        context['last_news'] = News.objects.last()
        return context


class AuthorizationCreateView(CreateView):  # pylint: disable=R0901
    model = EventAuthorization
    form_class = AuthorizationForm

    @method_decorator(promoter_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.event = get_object_or_404(
            Event,
            pk=self.kwargs['event_pk']
        )
        return super(AuthorizationCreateView, self).form_valid(form)

    def get_success_url(self):
        try:
            self.object.event.authorizednonmotorizedevent
        except:
            try:
                self.object.event.motorizedconcentration
            except:
                try:
                    self.object.event.motorizedevent
                except:
                    try:
                        self.object.event.motorizedrace
                    except:
                        pass
                    else:
                        return reverse('events:motorizedrace_detail', kwargs={'pk': self.object.event.pk})
                else:
                    return reverse('events:motorizedevent_detail', kwargs={'pk': self.object.event.pk})
            else:
                return reverse('events:motorizedconcentration_detail', kwargs={'pk': self.object.event.pk})
        else:
            return reverse('events:authorizednonmotorizedevent_detail', kwargs={'pk': self.object.event.pk})


class AuthorizationDetailView(DetailView):  # pylint: disable=R0901
    model = EventAuthorization

    @method_decorator(instructor_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationDetailView, self).dispatch(*args, **kwargs)


class AuthorizationUpdateView(UpdateView):  # pylint: disable=R0901
    model = EventAuthorization
    form_class = AuthorizationDispatchForm
    success_url = "/authorizations/%(id)s"

    @method_decorator(instructor_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.dispatch()
        return super(AuthorizationUpdateView, self).form_valid(form)


class AuthorizationPublishBylawView(UpdateView):  # pylint: disable=R0901
    model = EventAuthorization
    form_class = AuthorizationPublishBylawForm
    template_name_suffix = '_publish_form'

    @method_decorator(instructor_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationPublishBylawView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.publish()
        return super(AuthorizationPublishBylawView, self).form_valid(form)

authorizations/templates/authorizations/eventauthorization_detail.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}
    {% trans "event authorization"|title %}
{% endblock %}

{% block page_title %}
    <h1>{{ object.event|capfirst }}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <ul class="nav nav-pills">
                <li class="active"><a href="#authorization" data-toggle="pill">{% trans "authorization"|capfirst %}</a></li>
                <li><a href="#event" data-toggle="pill">{% trans "event detail"|capfirst %}</a></li>
                {% include 'events/event_tabs.html' with object=object.event %}
            </ul>
            <div class="tab-content">
                <div id="authorization" class="panel panel-default tab-pane fade in active">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ object.event|capfirst }}
                        </h3>
                    </div>
                    <ul class="list-group">
                        {% if object.event.creation_date %}
                            <li class="list-group-item">{% trans "event creation date"|capfirst %} : {{ object.event.creation_date }}</li>
                      	{% endif %}
                        <li class="list-group-item">{% trans "authorization request date"|capfirst %} : {{ object.creation_date }}</li>
                        <li class="list-group-item">{% trans "type of event"|capfirst %} : {{ object }}</li>
                        {% if object.bylaw %}
                            <li class="list-group-item">{% trans "bylaw"|capfirst %} : <a href="{{ object.bylaw.url }}" target='_blank'>{{ object.bylaw }}</a></li>
                        {% endif %}
                    </ul>
                    {% for agreement in object.agreement_set.all %}
                        <div class="panel-heading">
                            <h3 class="panel-title">{% trans 'agreement'|capfirst %} : 
                                {% if agreement.serviceagreement %}
                                    {{ agreement.serviceagreement.service }}
                                {% elif agreement.federalagreement %}
                                    {{ agreement.federalagreement.get_federation }}
                                {% elif agreement.townhallagreement %}
                                    {{ agreement.townhallagreement.commune }}
                                {% elif agreement.edsragreement %}
                                    {{ agreement.edsragreement.get_edsr }}
                                {% elif agreement.sdisagreement %}
                                    {{ agreement.sdisagreement.get_sdis }}
                                {% elif agreement.ddspagreement %}
                                    {{ agreement.ddspagreement.get_ddsp }}
                                {% elif agreement.cgagreement %}
                                    {{ agreement.cgagreement.get_general_council }}
                                {% endif %}
                                {% if agreement.state != 'acknowledged' and object.state != 'published' %}
                                    {% if agreement.serviceagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:service_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.federalagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:federal_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.townhallagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:townhall_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.edsragreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:edsr_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.sdisagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:sdis_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.ddspagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:ddsp_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% elif agreement.cgagreement %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:cg_agreement_resend' pk=agreement.pk %}" role="button">{% trans 'Raise agreement request' %}</a>
                                    {% endif %}
                                {% endif %}
                            </h3>
                        </div>
                        <ul class="list-group">
                            <li class="list-group-item">{% trans "agreement has been sent the"|capfirst %} {{ agreement.request_date }}</li>
                            {% ifnotequal agreement.state 'acknowledged' %}
                                <li class="list-group-item">{% trans "agreement is under review"|capfirst %}</li>
                            {% else %}
                                <li class="list-group-item">{% trans "agreement date"|capfirst %} : {{ agreement.reply_date }}</li>
                                <li class="list-group-item">{% trans "favorable"|capfirst %} : {{ agreement.favorable|yesno|title }}</li>
                                <li class="list-group-item">{% trans "prescriptions"|capfirst %} : {{ agreement.prescriptions|linebreaks }}</li>
                                {% if agreement.attached_document %}
                                    <li class="list-group-item">{% trans "attached document"|capfirst %} : 
                                        <a href="{{ agreement.attached_document.url }}" target='_blank'>{{ agreement.attached_document }}</a>
                                    </li>
                                {% endif %}
                            {% endifnotequal %}
                        </ul>
                    {% endfor %}
                </div>
                {% include 'events/event_panel_instructor.html' with object=object.event %}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans "actions available"|capfirst %}</h3>
                </div>
                <div class="panel-body">
                    <p>{% trans "find here all actions available related to this event"|capfirst %}</p>
                </div>
                <ul class="list-group">
                    {% if object.state != 'published' %}
                        <li class="list-group-item">
                            <a href="{% url 'events:additional_data_add' event_pk=object.event.id %}" class="btn" role="button">
                                {% trans "request more information"|capfirst %}
                            </a>
                        </li>
                    {% endif %}
                    {% if object.state == 'created' %}
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_update' pk=object.id %}" class="btn" role="button">
                                {% trans "dispatch agreements requests"|capfirst %}
                            </a>
                        </li>
                    {% elif object.state == 'dispatched' %}
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_update' pk=object.id %}" class="btn" role="button">
                                {% trans "add agreements requests"|capfirst %}
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_publish' pk=object.id %}" class="btn" role="button">
                                {% trans "publish bylaw"|capfirst %}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <a href="{% url 'authorizations:dashboard' %}" class="btn" role="button">
                {% trans "go back to the dashboard"|capfirst %}
            </a>
        </div>
    </div>
{% endblock %}

authorizations/templates/authorizations/eventauthorization_form.html
{% extends "events/base_form.html" %}

{% load i18n %}
{% load staticfiles %}

{% block head_title %}
    {% trans "event authorization"|capfirst %}
{% endblock %}

{% block page_title %}
    <h1>{% trans "event authorization"|capfirst %}</h1>
{% endblock %}

{% block extra_js %}
    <script src='{% static 'events/js/bootstrap-multiselect.js' %}'></script>
    <link href='{% static 'events/css/bootstrap-multiselect.css' %}' rel='stylesheet' type='text/css'>
    <script src='{% static 'authorizations/js/bootstrap-multiselect-authorizations.js' %}'></script>
{% endblock %}

authorizations/templates/authorizations/eventauthorization_list.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}
    {% trans "instructor dashboard"|title %}
{% endblock %}

{% block page_title %}
    {% include "events/last_news.html" %}
    <h1><i class="fa fa-tasks"></i> {% trans "dashboard"|title %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>{% trans 'authorizations requested'|capfirst %}</h3>

            <div class="panel panel-default authorizations-requested">
                <div class="list-group">
                    {% for authorization in object_list %}
                        <a class="list-group-item 
                            {% if authorization.state == 'published' %}
                                list-group-item-success
                            {% elif authorization.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif authorization.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'authorizations:authorization_detail' authorization.id %}">{{ authorization.event.begin_date|date:"d/m/Y" }} : {{ authorization.event }}
                            {% if not authorization.state == 'created' %}
                                {% if authorization.all_agreements_validated %}
                                    <span class="label label-success top-right"><i class="fa fa-check"></i></span>
                                {% else %}
                                    <span class="label label-default top-right">{{ authorization.agreements_missing }} {% trans 'missing agreements' %}</span>
                                {% endif %}
                            {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">{% trans 'No authorizations to manage' %}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h3>{% trans 'declarations'|capfirst %}</h3>

            <div class="panel panel-default declarations">
                <div class="list-group">
                    {% for declaration in declarations %}
                        <a class="list-group-item
                            {% if declaration.state == 'published' %}
                                list-group-item-success
                            {% elif declaration.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'declarations:declaration_detail' declaration.id %}">{{ declaration.event.begin_date|date:"d/m/Y" }}
                            : {{ declaration.event }}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">{% trans 'No declarations to manage' %}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        {% include "notifications/actions_list.html" %}
    </div>
    <div class="col-sm-6">
        {% include "notifications/notifications_list.html" %}
    </div>
    </div>
{% endblock %}

authorizations/templates/authorizations/eventauthorization_publish_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}{% trans "bylaw publishing"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "bylaw publishing"|capfirst %}</h1>
{% endblock %}