ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.sitemaps import FlatPageSitemap

from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    'django.contrib.flatpages.views', (r'^(?P<url>.*/)$', 'flatpage'),
)

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import EventChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclaredNonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from .views import EventPublicDetail

from .views import DeclaredNonMotorizedEventCreate
from .views import DeclaredNonMotorizedEventDetail
from .views import DeclaredNonMotorizedEventUpdate

from .views import AuthorizedNonMotorizedEventCreate
from .views import AuthorizedNonMotorizedEventDetail
from .views import AuthorizedNonMotorizedEventUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import AdditionalDataRequestView
from .views import AdditionalDataProvideView

from .views import MailToPromotersView
from .views import MailToTownHallsView
from .views import NewsListView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToPromotersView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^news/$', NewsListView.as_view(), name="news_list"),
    url(r'^calendar/(?P<activity>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', EventChoose.as_view(),
        name='event_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^declarednonmotorizedevents/choose',
        DeclaredNonMotorizedEventChoose.as_view(),
        name="declarednonmotorizedevent_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        EventPublicDetail.as_view(),
        name="event_detail"),

    # DeclaredNonMotorizedEvent urls
    url(r'^declarednonmotorizedevents/add/$',
        DeclaredNonMotorizedEventCreate.as_view(),
        name="declarednonmotorizedevent_add"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/$',
        DeclaredNonMotorizedEventDetail.as_view(),
        name="declarednonmotorizedevent_detail"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/edit/$',
        DeclaredNonMotorizedEventUpdate.as_view(),
        name="declarednonmotorizedevent_update"),

    # AuthorizedNonMotorizedEvent urls
    url(r'^authorizednonmotorizedevents/add/$',
        AuthorizedNonMotorizedEventCreate.as_view(),
        name="authorizednonmotorizedevent_add"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/$',
        AuthorizedNonMotorizedEventDetail.as_view(),
        name="authorizednonmotorizedevent_detail"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/edit/$',
        AuthorizedNonMotorizedEventUpdate.as_view(),
        name="authorizednonmotorizedevent_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<event_pk>\d+)/additional_data/add$',
        AdditionalDataRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        AdditionalDataProvideView.as_view(),
        name="additional_data_provide"),
    # pylint: enable=E1120
)

sub_agreements/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from sub_agreements.views import EDSRSubAgreementDetail, EDSRSubAgreementAcknowledge, NotifyEDSRAgentsView
from .views import Dashboard

from .views import CGDSubAgreementAcknowledge
from .views import CGDSubAgreementDetail
from .views import NotifyBrigadesView

from .views import CompanySubAgreementAcknowledge
from .views import CompanySubAgreementDetail
from .views import NotifyCISView

from .views import CommissariatSubAgreementAcknowledge
from .views import CommissariatSubAgreementDetail

from .views import CGServiceSubAgreementAcknowledge
from .views import CGServiceSubAgreementDetail

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^dashboard/$', Dashboard.as_view(),
        name='dashboard'),
    # CGD SubAgreements
    url(r'^cgd/(?P<pk>\d+)/$',
        CGDSubAgreementDetail.as_view(),
        name='cgd_subagreement_detail'),
    url(r'^cgd/(?P<pk>\d+)/acknowledge/$',
        CGDSubAgreementAcknowledge.as_view(),
        name='cgd_subagreement_acknowledge'),
    url(r'^cgd/(?P<pk>\d+)/notify_brigades/$',
        NotifyBrigadesView.as_view(),
        name='notify_brigades'),
    # EDSR SubAgreements
    url(r'^edsr/(?P<pk>\d+)/$',
        EDSRSubAgreementDetail.as_view(),
        name='edsr_subagreement_detail'),
    url(r'^edsr/(?P<pk>\d+)/acknowledge/$',
        EDSRSubAgreementAcknowledge.as_view(),
        name='edsr_subagreement_acknowledge'),
    url(r'^edsr/(?P<pk>\d+)/notify_agents/$',
        NotifyEDSRAgentsView.as_view(),
        name='notify_edsr_agents'),
    # Company SubAgreements
    url(r'^company/(?P<pk>\d+)/$',
        CompanySubAgreementDetail.as_view(),
        name='company_subagreement_detail'),
    url(r'^company/(?P<pk>\d+)/acknowledge/$',
        CompanySubAgreementAcknowledge.as_view(),
        name='company_subagreement_acknowledge'),
    url(r'^company/(?P<pk>\d+)/notify_cis/$',
        NotifyCISView.as_view(),
        name='notify_cis'),
    # Commissariat SubAgreements
    url(r'^commissariat/(?P<pk>\d+)/$',
        CommissariatSubAgreementDetail.as_view(),
        name='commissariat_subagreement_detail'),
    url(r'^commissariat/(?P<pk>\d+)/acknowledge/$',
        CommissariatSubAgreementAcknowledge.as_view(),
        name='commissariat_subagreement_acknowledge'),
    # CG Service SubAgreements
    url(r'^cgservice/(?P<pk>\d+)/$',
        CGServiceSubAgreementDetail.as_view(),
        name='cgservice_subagreement_detail'),
    url(r'^cgservice/(?P<pk>\d+)/acknowledge/$',
        CGServiceSubAgreementAcknowledge.as_view(),
        name='cgservice_subagreement_acknowledge'),
)

sub_agreements/forms.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

from ddcs_loire.utils import GenericForm

from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from sub_agreements.models import EDSRSubAgreement
from .models import SubAgreement
from .models import CompanySubAgreement
from .models import CGDSubAgreement


class SubAgreementForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = SubAgreement
        fields = ('favorable', 'prescriptions',)

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(SubAgreementForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'favorable',
            'prescriptions',
            FormActions(
                Submit('save', _('acknowledge subagreement').capitalize())
            )
        )


class NotifyCISForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = CompanySubAgreement
        fields = ('concerned_cis',)

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(NotifyCISForm, self).__init__(*args, **kwargs)
        self.fields['concerned_cis'].queryset = self.instance.company.fireservice_set.all()  # noqa pylint: disable=E1101
        self.helper.layout = Layout(
            'concerned_cis',
            FormActions(
                Submit('save', _('notify concerned cis').capitalize())
            )
        )


class NotifyBrigadesForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = CGDSubAgreement
        fields = ('concerned_brigades',)

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(NotifyBrigadesForm, self).__init__(*args, **kwargs)
        self.fields['concerned_brigades'].queryset = self.instance.gendarmerie_company.brigade_set.all()  # noqa pylint: disable=E1101
        self.helper.layout = Layout(
            'concerned_brigades',
            FormActions(
                Submit('save', _('notify concerned brigades').capitalize())
            )
        )

sub_agreements/templates/sub_agreements/cgdsubagreement_detail.html
{% extends "sub_agreements/subagreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' or object.state == 'notified' %}
        <a href="{% url 'sub_agreements:notify_brigades' pk=object.id %}" class="btn" role="button">
            {% trans "notify concerned brigades"|capfirst %}
        </a>
    {% endif %}
    {% if object.state == 'notified' %}
        <a href="{% url 'sub_agreements:cgd_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge sub-agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/cgdsubagreement_notify_form.html
{% extends "sub_agreements/subagreement_form.html" %}

{% load i18n %}

{% block head_title %}{% trans "choose concerned brigades"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "choose concerned brigades"|capfirst %}</h1>
{% endblock %}

sub_agreements/templates/sub_agreements/cgservicesubagreement_ack_form.html
{% extends "sub_agreements/subagreement_form.html" %}

sub_agreements/templates/sub_agreements/cgservicesubagreement_detail.html
{% extends "sub_agreements/subagreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:cgservice_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge sub-agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/cgservicesubagreement_list.html
{% extends "sub_agreements/subagreement_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:cgservice_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/commissariatsubagreement_ack_form.html
{% extends "sub_agreements/subagreement_form.html" %}

sub_agreements/templates/sub_agreements/commissariatsubagreement_detail.html
{% extends "sub_agreements/subagreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:commissariat_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge sub-agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/commissariatsubagreement_list.html
{% extends "sub_agreements/subagreement_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:commissariat_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/companysubagreement_ack_form.html
{% extends "sub_agreements/subagreement_form.html" %}

sub_agreements/templates/sub_agreements/companysubagreement_detail.html
{% extends "sub_agreements/subagreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:company_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge sub-agreement"|capfirst %}
        </a>
    {% elif object.state == 'acknowledged' and object.agreement.state == 'acknowledged' and not object.concerned_cis.exists %}
        <a href="{% url 'sub_agreements:notify_cis' pk=object.id %}" class="btn" role="button">
            {% trans "notify concerned cis"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/companysubagreement_list.html
{% extends "sub_agreements/subagreement_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:company_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/companysubagreement_notify_form.html
{% extends "sub_agreements/subagreement_form.html" %}

{% load i18n %}

{% block head_title %}{% trans "choose concerned cis"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "choose concerned cis"|capfirst %}</h1>
{% endblock %}

sub_agreements/templates/sub_agreements/subagreement_detail.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% endblock %}
{% block page_title %}
    <h1>{{ object.agreement.authorization.event|capfirst }}</h1>
    {% ifequal object.agreement.state 'created' %}
        {% if not object.agreement.delay_exceeded %}
            <div class="alert alert-warning">
                <p><strong>{% trans 'attention'|capfirst %} ! </strong>
                    {% trans 'you have until'|capfirst %} {{ object.agreement.get_deadline|date:'d F Y' }}, {% trans 'to give your agreement' %}
                </p>
            </div>
        {% else %}
            <div class="alert alert-danger">
                <p><strong>{% trans 'attention'|capfirst %} ! </strong>
                    {% trans "it is now too late to give your sub-agreement to this event."|capfirst %}.<br/>
                    {% trans "instructor won't have to take your sub-agreement into account when authorizing or not the event."|capfirst %}
                </p>
            </div>
        {% endif %}
    {% endifequal %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <ul class="nav nav-pills">
                <li class="active"><a href="#subagreement" data-toggle="pill">{% trans "sub-agreement"|capfirst %}</a></li>
                <li><a href="#event" data-toggle="pill">{% trans "event detail"|capfirst %}</a></li>
                {% include 'events/event_tabs.html' with object=object.agreement.authorization.event %}
            </ul>
            <div class="tab-content">
                <div id="subagreement" class="panel panel-default tab-pane fade in active">
                    {% include 'agreements/agreement_description.html' %}
                </div>
                {% include 'events/event_panel_instructor.html' with object=object.agreement.authorization.event %}
            </div>
        </div>
        <div class="col-sm-4">
            {% if object.agreement.authorization.state == 'published' and object.agreement.authorization.bylaw %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% trans "bylaw has been published"|capfirst %}</h3>
                    </div>
                    <div class="panel-body">
                        <p>{% trans "you can download it by clicking on the link below" %}</p>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{{ object.agreement.authorization.bylaw.url }}" target='_blank'>{% trans 'bylaw'|capfirst %}</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% trans "actions available"|capfirst %}</h3>
                    </div>
                    <div class="panel-body">
                        <p>{% trans "find here all actions available related to this event"|capfirst %}</p>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            {% block agreement_actions %}{% endblock %}
                        </li>
                    </ul>
                </div>
            {% endif %}
            <a href="{% url 'sub_agreements:dashboard' %}" class="btn" role="button">
                {% trans "go back to the dashboard"|capfirst %}
            </a>
        </div>
    </div>
{% endblock %}

sub_agreements/templates/sub_agreements/subagreement_list.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}
    {% trans "dashboard"|title %}
{% endblock %}

{% block page_title %}
    {% include "events/last_news.html" %}
    <h1>{% trans "dashboard"|title %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>{% trans 'sub agreements requested'|capfirst %}</h3>
            <div class="panel panel-default">
                <div class="list-group">
                    {% for sub_agreement in object_list %}
                        <a class="list-group-item 
                            {% if sub_agreement.state == 'acknowledged' %}
                                list-group-item-success
                            {% elif sub_agreement.state == 'notified' %}
                                list-group-item-warning
                            {% elif sub_agreement.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            " 
                            {% block subagreement_item %}{% endblock %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">{% trans 'No sub-agreements to manage' %}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                {% include "notifications/actions_list.html" %}
            <div class="row">
            </div>
                {% include "notifications/notifications_list.html" %}
            </div>
        </div>
    </div>
{% endblock %}