agreements/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from agreements.views import GGDAgreementDispatch, GGDAgreementDetail, GGDAgreementFormat, GGDAgreementAcknowledge, GGDAgreementResend
from .views import Dashboard

from .views import EDSRAgreementDispatch
from .views import EDSRAgreementDetail
from .views import EDSRAgreementFormat
from .views import EDSRAgreementAcknowledge
from .views import EDSRAgreementResend

from .views import SDISAgreementDispatch
from .views import SDISAgreementDetail
from .views import SDISAgreementAcknowledge
from .views import SDISAgreementResend

from .views import DDSPAgreementDispatch
from .views import DDSPAgreementDetail
from .views import DDSPAgreementAcknowledge
from .views import DDSPAgreementResend

from .views import CGAgreementDispatch
from .views import CGAgreementDetail
from .views import CGAgreementFormat
from .views import CGAgreementAcknowledge
from .views import CGAgreementResend

from .views import ServiceAgreementDetail
from .views import ServiceAgreementAcknowledge
from .views import ServiceAgreementResend

from .views import FederalAgreementDetail
from .views import FederalAgreementAcknowledge
from .views import FederalAgreementResend

from .views import TownHallAgreementDetail
from .views import TownHallAgreementAcknowledge
from .views import TownHallAgreementResend


urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^dashboard/$', Dashboard.as_view(),
        name='dashboard'),

    # Service Agreements
    url(r'^service/(?P<pk>\d+)/$', ServiceAgreementDetail.as_view(),
        name='service_agreement_detail'),
    url(r'^service/(?P<pk>\d+)/acknowledge/$',
        ServiceAgreementAcknowledge.as_view(),
        name='service_agreement_acknowledge'),
    url(r'^service/(?P<pk>\d+)/resend/$', ServiceAgreementResend.as_view(),
        name='service_agreement_resend'),
    # Federal Agreements
    url(r'^federation/(?P<pk>\d+)/$', FederalAgreementDetail.as_view(),
        name='federal_agreement_detail'),
    url(r'^federation/(?P<pk>\d+)/acknowledge/$',
        FederalAgreementAcknowledge.as_view(),
        name='federal_agreement_acknowledge'),
    url(r'^federation/(?P<pk>\d+)/resend/$', FederalAgreementResend.as_view(),
        name='federal_agreement_resend'),
    # TownHall Agreements
    url(r'^townhall/(?P<pk>\d+)/$', TownHallAgreementDetail.as_view(),
        name='townhall_agreement_detail'),
    url(r'^townhall/(?P<pk>\d+)/acknowledge/$',
        TownHallAgreementAcknowledge.as_view(),
        name='townhall_agreement_acknowledge'),
    url(r'^townhall/(?P<pk>\d+)/resend/$', TownHallAgreementResend.as_view(),
        name='townhall_agreement_resend'),
    # EDSR Agreements
    url(r'^edsr/(?P<pk>\d+)/dispatch/$', EDSRAgreementDispatch.as_view(),
        name='edsr_agreement_dispatch'),
    url(r'^edsr/(?P<pk>\d+)/$', EDSRAgreementDetail.as_view(),
        name='edsr_agreement_detail'),
    url(r'^edsr/(?P<pk>\d+)/format/$', EDSRAgreementFormat.as_view(),
        name='edsr_agreement_format'),
    url(r'^edsr/(?P<pk>\d+)/acknowledge/$',
        EDSRAgreementAcknowledge.as_view(),
        name='edsr_agreement_acknowledge'),
    url(r'^edsr/(?P<pk>\d+)/resend/$', EDSRAgreementResend.as_view(),
        name='edsr_agreement_resend'),
    # GGD Agreements
    url(r'^ggd/(?P<pk>\d+)/dispatch/$', GGDAgreementDispatch.as_view(),
        name='ggd_agreement_dispatch'),
    url(r'^ggd/(?P<pk>\d+)/$', GGDAgreementDetail.as_view(),
        name='ggd_agreement_detail'),
    url(r'^ggd/(?P<pk>\d+)/format/$', GGDAgreementFormat.as_view(),
        name='ggd_agreement_format'),
    url(r'^ggd/(?P<pk>\d+)/acknowledge/$', GGDAgreementAcknowledge.as_view(),
        name='ggd_agreement_acknowledge'),
    url(r'^ggd/(?P<pk>\d+)/resend/$', GGDAgreementResend.as_view(),
        name='ggd_agreement_resend'),
    # SDIS Agreements
    url(r'^sdis/(?P<pk>\d+)/dispatch/$', SDISAgreementDispatch.as_view(),
        name='sdis_agreement_dispatch'),
    url(r'^sdis/(?P<pk>\d+)/$', SDISAgreementDetail.as_view(),
        name='sdis_agreement_detail'),
    url(r'^sdis/(?P<pk>\d+)/acknowledge/$',
        SDISAgreementAcknowledge.as_view(),
        name='sdis_agreement_acknowledge'),
    url(r'^sdis/(?P<pk>\d+)/resend/$', SDISAgreementResend.as_view(),
        name='sdis_agreement_resend'),
    # DDSP Agreements
    url(r'^ddsp/(?P<pk>\d+)/dispatch/$', DDSPAgreementDispatch.as_view(),
        name='ddsp_agreement_dispatch'),
    url(r'^ddsp/(?P<pk>\d+)/$', DDSPAgreementDetail.as_view(),
        name='ddsp_agreement_detail'),
    url(r'^ddsp/(?P<pk>\d+)/acknowledge/$',
        DDSPAgreementAcknowledge.as_view(),
        name='ddsp_agreement_acknowledge'),
    url(r'^ddsp/(?P<pk>\d+)/resend/$', DDSPAgreementResend.as_view(),
        name='ddsp_agreement_resend'),
    # CG Agreements
    url(r'^cg/(?P<pk>\d+)/dispatch/$', CGAgreementDispatch.as_view(),
        name='cg_agreement_dispatch'),
    url(r'^cg/(?P<pk>\d+)/$', CGAgreementDetail.as_view(),
        name='cg_agreement_detail'),
    url(r'^cg/(?P<pk>\d+)/format/$', CGAgreementFormat.as_view(),
        name='cg_agreement_format'),
    url(r'^cg/(?P<pk>\d+)/acknowledge/$',
        CGAgreementAcknowledge.as_view(),
        name='cg_agreement_acknowledge'),
    url(r'^cg/(?P<pk>\d+)/resend/$', CGAgreementResend.as_view(),
        name='cg_agreement_resend'),
)

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.sitemaps import FlatPageSitemap

from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    'django.contrib.flatpages.views', (r'^(?P<url>.*/)$', 'flatpage'),
)

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import EventChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclaredNonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from .views import EventPublicDetail

from .views import DeclaredNonMotorizedEventCreate
from .views import DeclaredNonMotorizedEventDetail
from .views import DeclaredNonMotorizedEventUpdate

from .views import AuthorizedNonMotorizedEventCreate
from .views import AuthorizedNonMotorizedEventDetail
from .views import AuthorizedNonMotorizedEventUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import AdditionalDataRequestView
from .views import AdditionalDataProvideView

from .views import MailToPromotersView
from .views import MailToTownHallsView
from .views import NewsListView

urlpatterns = patterns(
    # pylint: disable=E1120
    '',
    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToPromotersView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^news/$', NewsListView.as_view(), name="news_list"),
    url(r'^calendar/(?P<activity>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', EventChoose.as_view(),
        name='event_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^declarednonmotorizedevents/choose',
        DeclaredNonMotorizedEventChoose.as_view(),
        name="declarednonmotorizedevent_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        EventPublicDetail.as_view(),
        name="event_detail"),

    # DeclaredNonMotorizedEvent urls
    url(r'^declarednonmotorizedevents/add/$',
        DeclaredNonMotorizedEventCreate.as_view(),
        name="declarednonmotorizedevent_add"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/$',
        DeclaredNonMotorizedEventDetail.as_view(),
        name="declarednonmotorizedevent_detail"),
    url(r'^declarednonmotorizedevents/(?P<pk>\d+)/edit/$',
        DeclaredNonMotorizedEventUpdate.as_view(),
        name="declarednonmotorizedevent_update"),

    # AuthorizedNonMotorizedEvent urls
    url(r'^authorizednonmotorizedevents/add/$',
        AuthorizedNonMotorizedEventCreate.as_view(),
        name="authorizednonmotorizedevent_add"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/$',
        AuthorizedNonMotorizedEventDetail.as_view(),
        name="authorizednonmotorizedevent_detail"),
    url(r'^authorizednonmotorizedevents/(?P<pk>\d+)/edit/$',
        AuthorizedNonMotorizedEventUpdate.as_view(),
        name="authorizednonmotorizedevent_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<event_pk>\d+)/additional_data/add$',
        AdditionalDataRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        AdditionalDataProvideView.as_view(),
        name="additional_data_provide"),
    # pylint: enable=E1120
)

agreements/forms.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

from agreements.models import GGDAgreement
from ddcs_loire.utils import GenericForm

from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from .models import Agreement
from .models import CGAgreement
from .models import DDSPAgreement
from .models import EDSRAgreement
from .models import SDISAgreement


class AgreementForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = Agreement
        fields = ('favorable', 'prescriptions', 'attached_document')

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(AgreementForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'favorable',
            'prescriptions',
            'attached_document',
            FormActions(
                Submit('save', _('acknowledge agreement').capitalize())
            )
        )


class AgreementFormatForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = Agreement
        fields = ('favorable', 'prescriptions', 'attached_document')

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(AgreementFormatForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'favorable',
            'prescriptions',
            'attached_document',
            FormActions(
                Submit('save', _('format agreement').capitalize())
            )
        )


class DDSPAgreementDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = DDSPAgreement
        fields = ('concerned_commissariat', )

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(DDSPAgreementDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'concerned_commissariat',
            FormActions(
                Submit('save', _('send sub-agreements request').capitalize())
            )
        )


class EDSRAgreementDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = EDSRAgreement
        fields = ('concerned_cgd', )

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(EDSRAgreementDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'concerned_cgd',
            FormActions(
                Submit('save', _('send sub-agreements request').capitalize())
            )
        )


class GGDAgreementDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = GGDAgreement
        fields = ('concerned_cgd', 'concerned_edsr')

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(GGDAgreementDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'concerned_cgd',
            'concerned_edsr',
            FormActions(
                Submit('save', _('send sub-agreements request').capitalize())
            )
        )


class SDISAgreementDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = SDISAgreement
        fields = ('concerned_company', )

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(SDISAgreementDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'concerned_company',
            FormActions(
                Submit('save', _('send sub-agreements request').capitalize())
            )
        )


class CGAgreementDispatchForm(GenericForm):

    class Meta:  # pylint: disable=C1001
        model = CGAgreement
        fields = ('concerned_services', )

    def __init__(self, *args, **kwargs):  # pylint: disable=E1002
        super(CGAgreementDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'concerned_services',
            FormActions(
                Submit('save', _('send sub-agreements request').capitalize())
            )
        )

agreements/templates/agreements/agreement_list.html
{% extends "events/base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}
    {% trans "dashboard"|title %}
{% endblock %}

{% block page_title %}
    {% include "events/last_news.html" %}
    <h1>{% trans "dashboard"|title %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>{% trans 'agreements requested'|capfirst %}</h3>

            <div class="panel panel-default">
                <div class="list-group">
                    {% for agreement in object_list %}
                        <a class="list-group-item 
                            {% if agreement.state == 'acknowledged' %}
                                list-group-item-success
                            {% elif agreement.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif agreement.state == 'formatted' %}
                                list-group-item-warning
                            {% elif agreement.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                        {% block agreement_item %}{% endblock %}
                        {% if agreement.get_days_left_before_deadline.days > 0 and not agreement.state == 'acknowledged' %}
                            <span class="label label-default pull-right">{% trans 'delay' %} : {{ agreement.get_days_left_before_deadline.days }} {% trans 'days' %}</span>
                        {% endif %}
                        {% if agreement.sub_agreements_missing %}
                            <span class="label label-default pull-right">{{ agreement.sub_agreements_missing }} {% trans 'missing sub-agreement' %}</span>
                        {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">{% trans 'No agreements to manage' %}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        {% include "notifications/actions_list.html" %}
    </div>
    <div class="col-sm-6">
        {% include "notifications/notifications_list.html" %}
    </div>
    </div>
{% endblock %}

agreements/templates/agreements/cgagreement_dispatch_form.html
{% extends "agreements/agreement_dispatch_form.html" %}

agreements/templates/agreements/cgagreement_list.html
{% extends "agreements/agreement_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:cg_agreement_detail' agreement.id %}">
        {{ agreement.authorization.event.begin_date|date:"d/m/Y" }} : {{ agreement.authorization.event }}
{% endblock %}

agreements/templates/agreements/ddspagreement_ack_form.html
{% extends "agreements/agreement_ack_form.html" %}

agreements/templates/agreements/ddspagreement_detail.html
{% extends "agreements/agreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'agreements:ddsp_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            {% trans "send sub-agreements requests"|capfirst %}
        </a>
    {% elif object.state == 'dispatched' %}
        {% if object.sub_agreements_validated %}
            <a href="{% url 'agreements:ddsp_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
                {% trans "acknowledge agreement"|capfirst %}
            </a>
        {% endif %}
    {% endif %}
{% endblock %}

agreements/templates/agreements/edsragreement_format_form.html
{% extends "agreements/agreement_format_form.html" %}

agreements/templates/agreements/federalagreement_detail.html
{% extends "agreements/agreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' and not object.delay_exceeded %}
        <a href="{% url 'agreements:federal_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/ggdagreement_ack_form.html
{% extends "agreements/agreement_ack_form.html" %}

agreements/templates/agreements/ggdagreement_detail.html
{% extends "agreements/agreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' and request.user.agent.edsragent %}
        <a href="{% url 'agreements:ggd_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            {% trans "send sub-agreements requests"|capfirst %}
        </a>
    {% elif object.state == 'dispatched' and request.user.agent.edsragent %}
        {% if object.sub_agreements_validated %}
            <a href="{% url 'agreements:ggd_agreement_format' pk=object.id %}" class="btn" role="button">
                {% trans "format agreement"|capfirst %}
            </a>
        {% endif %}
    {% elif object.state == 'formatted' and request.user.agent.ggdagent%}
        <a href="{% url 'agreements:ggd_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/sdisagreement_ack_form.html
{% extends "agreements/agreement_ack_form.html" %}

agreements/templates/agreements/serviceagreement_ack_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}{% trans "acknowledge agreement"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "acknowledge agreement"|capfirst %}</h1>
{% endblock %}

agreements/templates/agreements/serviceagreement_detail.html
{% extends "agreements/agreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'agreements:service_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/townhallagreement_ack_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}{% trans "acknowledge agreement"|capfirst %}{% endblock %}
{% block page_title %}
    <h1>{% trans "acknowledge agreement"|capfirst %}</h1>
{% endblock %}

agreements/templates/agreements/townhallagreement_detail.html
{% extends "agreements/agreement_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'agreements:townhall_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            {% trans "acknowledge agreement"|capfirst %}
        </a>
    {% endif %}
{% endblock %}